# Generated by Django 4.2.3 on 2023-08-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230803_0809'),
    ]

    operations = [
    ]
