# Generated by Django 4.2.3 on 2023-08-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230803_0816'),
    ]

    operations = [
    ]
