# Generated by Django 4.2.3 on 2023-08-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230803_0907'),
    ]

    operations = [
    ]
