FROM python:3.10

# ARG AZURE_SERVER_NAME
# ARG AZURE_SERVER_USER
# ARG AZURE_SERVER_PASSWORD
# ARG AZURE_SERVER_HOST
# ARG AZURE_DB_NAME

# install necessary tools
RUN apt-get update && \
    apt-get install -y curl gnupg lsb-release

COPY odbc.sh /odbc.sh

RUN chmod +x /odbc.sh

# run the script as root
RUN /odbc.sh

RUN apt-get -y install unixodbc
RUN apt-get -y install unixodbc-dev
RUN apt-get install -y odbcinst1debian2
RUN apt-get install -f
RUN odbcinst -j
RUN find / -name "libmsodbcsql*"
RUN find / -name "libmsodbcsql*" > /emplacement.txt
RUN cat /pa.txt




ENV PYTHONUNBUFFERED 1
ENV ODBCSYSINI=/usr/lib/x86_64-linux-gnu/odbc
ENV ODBCINI=/usr/lib/x86_64-linux-gnu/odbc/odbc.ini


WORKDIR /code

COPY requirements.txt /code/


RUN pip install -r requirements.txt

COPY . /code/
