

# ARG AZURE_SERVER_NAME
# ARG AZURE_SERVER_USER
# ARG AZURE_SERVER_PASSWORD
# ARG AZURE_SERVER_HOST
# ARG AZURE_DB_NAME

# COPY odbc.sh /odbc.sh

# RUN chmod +x /odbc.sh

# # run the script as root
# RUN /odbc.sh

# # install necessary tools
# RUN apt-get update -y && apt-get install -y gcc curl gnupg build-essential

# Utilisez une image de base Python:3.10 (basée sur Debian)
FROM python:3.

# Mettez à jour et installez les outils nécessaires
RUN apt-get update && apt-get install -y \
    curl \
    apt-transport-https \
    gnupg2 \
    software-properties-common \
    unixodbc-dev \
    libgssapi-krb5-2

# Ajoutez les clés et les dépôts Microsoft pour Debian 10 (Buster)
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list

# Mettez à jour à nouveau après l'ajout de nouveaux dépôts
RUN apt-get update

# Installez les outils Microsoft SQL Server
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools

# Définir la variable d'environnement pour mssql-tools
ENV PATH "$PATH:/opt/mssql-tools/bin"

ENV PYTHONUNBUFFERED 1
WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/
