FROM python:3.8

ARG

# install necessary tools
RUN apt-get update && \
    apt-get install -y curl gnupg lsb-release

COPY odbc.sh /odbc.sh

RUN chmod +x /odbc.sh

# run the script as root
RUN /odbc.sh

ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY requirements.txt /code/

RUN pip install -r requirements.txt

COPY . /code/
