FROM python:3.8

ENV PYTHONUNBUFFERED 1

# Installer ODBC 
RUN apt-get update && apt-get install -y unixodbc-dev
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get install -y msodbcsql17

# Configurer le LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH /usr/local/lib

WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/