FROM python:3.10

# ARG AZURE_SERVER_NAME
# ARG AZURE_SERVER_USER
# ARG AZURE_SERVER_PASSWORD
# ARG AZURE_SERVER_HOST
# ARG AZURE_DB_NAME

# COPY odbc.sh /odbc.sh

# RUN chmod +x /odbc.sh

# # run the script as root
# RUN /odbc.sh

# # install necessary tools
# RUN apt-get update -y && apt-get install -y gcc curl gnupg build-essential




ENV PYTHONUNBUFFERED 1
WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/