FROM python:3.8

ENV PYTHONUNBUFFERED 1

WORKDIR /code

RUN apt-get update

COPY requirements.txt /code/

RUN pip install -r requirements.txt
RUN apt-get install -y unixodbc-dev python3-dev gcc
RUN pip install pyodbc
RUN apt-get install -y msodbcsql17

COPY . /code/