FROM python:3.8

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    unixodbc-dev \
    gcc \
    g++ \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /code


COPY requirements.txt /code/

RUN pip install -r requirements.txt

COPY . /code/