FROM python:3.8

ENV PYTHONUNBUFFERED 1

ARG AZURE_SERVER_NAME
ARG AZURE_SERVER_USER=
ARG AZURE_SERVER_PASSWORD=
ARG AZURE_SERVER_HOST=
ARG AZURE_DB_NAME

WORKDIR /code

RUN apt-get update
RUN apt-get install -y unixodbc-dev


COPY requirements.txt /code/

RUN pip install -r requirements.txt 

COPY . /code/