FROM python:3.10

# ARG AZURE_SERVER_NAME
# ARG AZURE_SERVER_USER
# ARG AZURE_SERVER_PASSWORD
# ARG AZURE_SERVER_HOST
# ARG AZURE_DB_NAME

# install necessary tools
RUN apt-get update && \
    apt-get install -y curl gnupg lsb-release

COPY odbc.sh /odbc.sh

RUN chmod +x /odbc.sh

# run the script as root
RUN /odbc.sh

RUN apt-get -y install unixodbc
RUN apt-get -y install unixodbc-dev
RUN apt-get install -y odbcinst1debian2
RUN apt-get install -f
RUN odbcinst -j
RUN find / -name "libmsodbcsql*" > /tmp/find_output.txt
RUN cat /tmp/find_output.txt





ENV PYTHONUNBUFFERED 1
WORKDIR /code

COPY requirements.txt /code/

RUN pip install -r requirements.txt

COPY . /code/
