FROM python:3.8

# Set buffer to make sure prints are shown on the console
ENV PYTHONUNBUFFERED 1

WORKDIR /code

# Set ARG for DB credentials
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD

# Update packages
RUN apt-get update -y

# Install necessary tools
RUN apt-get install -y apt-transport-https curl gnupg

# Add Microsoft's signing key
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

# Add Microsoft's SQL Server Ubuntu repository
RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list

# Update packages again
RUN apt-get update -y

# Install Microsoft's ODBC driver for SQL Server
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18

# Install optional command-line utilities for SQL Server
RUN ACCEPT_EULA=Y apt-get install -y mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"

# Copy requirements.txt and install requirements
COPY requirements.txt /code/
RUN pip install -r requirements.txt

# Copy code
COPY . /code/