FROM python:3.8

ARG AZURE_SERVER_NAME
ARG AZURE_SERVER_USER
ARG AZURE_SERVER_PASSWORD
ARGAZURE_SERVER_HOST
AZURE_DB_NAME

# install necessary tools
RUN apt-get update && \
    apt-get install -y curl gnupg lsb-release

COPY odbc.sh /odbc.sh

RUN chmod +x /odbc.sh

# run the script as root
RUN /odbc.sh

ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY requirements.txt /code/

RUN pip install -r requirements.txt

COPY . /code/
