FROM python:3.10

# ARG AZURE_SERVER_NAME
# ARG AZURE_SERVER_USER
# ARG AZURE_SERVER_PASSWORD
# ARG AZURE_SERVER_HOST
# ARG AZURE_DB_NAME

# install necessary tools
RUN apt-get upda
RUN apt-get update -y && apt-get install -y gcc curl gnupg build-essential
RUN apt-get install -y unixodbc-dev

COPY odbc.sh /odbc.sh

RUN chmod +x /odbc.sh

# run the script as root
RUN /odbc.sh

ENV PYTHONUNBUFFERED 1
WORKDIR /code

COPY requirements.txt /code/
RUN pip install --no-binary :all: pyodbc
RUN pip install -r requirements.txt

COPY . /code/