FROM python:3.8

ENV PYTHONUNBUFFERED 1

# Installer ODBC 
RUN apt-get update && apt-get install -y unixodbc-dev
RUN apt-get update && apt-get install -y msodbcsql17 --fix-missing

# Configurer le LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH /usr/local/lib

WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/