FROM python:3.10

RUN apt install curl
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN exit
RUN apt-get update
RUN echo msodbcsql18 msodbcsql/ACCEPT_EULA boolean true | debconf-set-selections
RUN ACCEPT_EULA=Y apt-get install -y mssql-tools18
RUN echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc \
    && /bin/bash -c "source ~/.bashrc"

ENV PYTHONUNBUFFERED 1
WORKDIR /code

COPY requirements.txt /code
RUN pip install -r requirements.txt


COPY . /code

RUN python manage.py collectstatic
CMD ["python", "manage.py", "runserver", "0.0.0.0:80"]